# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
