# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_deliveryboy_mongomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryBoy',
            new_name='DeliveryBoys',
        ),
    ]
