# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20170803_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoys',
        ),
    ]
