# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_delete_deliveryboys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoModel',
        ),
    ]
